# Generated by Django 3.0.5 on 2020-05-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='pub_date',
        ),
    ]
